#ifndef CUDASSL_CONFIG_H
#define CUDASSL_CONFIG_H

#define CUDASSL_SELF_TEST

#define CUDASSL_AES_C
#define CUDASSL_DES_C
#define CUDASSL_SHA1_C
#define CUDASSL_MD5_C
#define CUDASSL_MD4_C

#endif /* CUDASSL_CONFIG_H */
